openapi: 3.0.0
info:
  title: Accounting
  version: '1.0'
  description: This API connects to the accounting module of Digis
  contact:
    name: Johan Boissard
    email: johan@nexys.ch
    url: 'https://nexys.ch'
servers:
  - url: 'https://api.digis.io'
  - url: ''
    description: ''
paths:
  '/accounting/entry/{accountId}/list':
    get:
      summary: List of accounting entries for a selected account
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entry'
      operationId: 'get-accounting-entry-:accountId-list'
      description: list of entries for the selected account.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
    parameters:
      - schema:
          type: number
        name: accountId
        in: path
        description: account Id
        required: true
  '/accounting/account/{accountId}/detail':
    get:
      summary: Account detail
      tags: []
      responses: {}
      operationId: 'get-accounting-account-:accountId-detail'
      description: lists the details of a chosen account. The id is always numerical.
    parameters:
      - schema:
          type: number
        name: accountId
        in: path
        required: true
        description: id of the account
  '/accounting/account/:date/listUntil':
    get:
      summary: List of accounting entries until xxx-xx-xx
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-accounting-account-2018-12-31-listUntil
      description: 'same as `/account/list` but returns only until a given date. The date parameter is in the url and must be given in the ISO standard, e.g. 2019-10-30'
    parameters: []
  /accounting/account/list:
    get:
      summary: List of accounting entries
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
              examples: {}
      operationId: get-accounting-account-list
      description: get the list of accounts and their balance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas:
    Account:
      title: Account
      type: object
      description: Main account entity
      properties:
        id:
          type: string
        name:
          type: string
        number:
          type: number
        accountType:
          type: object
          properties:
            name:
              type: string
        currency:
          type: object
          properties:
            name:
              type: string
        total:
          type: number
        nTransactions:
          type: integer
        '':
          type: string
    Entry:
      title: Entry
      type: object
      properties:
        id:
          type: integer
        entryId:
          type: integer
        number:
          type: string
        direction:
          type: string
        description:
          type: string
        date:
          type: string
        currency:
          type: object
        account:
          type: object
        total:
          type: number
        csum:
          type: number
        entity:
          type: object
        '':
          type: string
  securitySchemes:
    Authorization:
      type: oauth2
